# Generated by Django 4.1.1 on 2023-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bulletin_delete_order_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='bg_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_images')),
            ],
        ),
    ]
