# Generated by Django 4.1.1 on 2023-01-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bg_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bg_img',
        ),
    ]
